spring:
  datasource:
    url: jdbc:mysql://localhost:3306/visualsecure
    username: root
    password:

  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: fb048c130a1016
    password: 8b5a599a9df4e3
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days



